### ISSUE TITLE
scaffold views need clickable links

### ISSUE THREAD

**Issue by goosetav** [spine/spine-rails#23]
without an href tag, the links aren't clickable (at least on mac/chome,safari,ff) -- either the A tags should have href="#" or use the routes to create the URLs

**Comment by maccman** [comment]
Surely that's something you can do with CSS?

**Comment by goosetav** [comment]
I don't think the browser will fire the click events without an href.
Under html5, A tags without hrefs are "placeholders" --
http://dev.w3.org/html5/html4-differences/Overview.html#changed-elements
-- but what that actually means isn't defined.

Its probably possible with CSS, but shouldn't the scaffold generator
should create a working system out of the box?

I'll play around and submit a patch for it.

-E

On 12/31/11 12:06 PM, "Alex MacCaw"
<reply+i-2695287-c4e3af1c845cf05a375e5d0713d2e22cdff08d86-57294@reply.githu
b.com> wrote:

**Comment by maccman** [comment]
The browser definitely fires a click event. It fires it on anything when it's clicked...

Are you saying that these links don't actually work? That's a different issue. If so, please do open a ticket for it.

**Comment by goosetav** [comment]
Yes, exactly, the links don't actually work -- the browser does not render
them as links, they don't highlight when hovering, the cursor doesn't
change and they don't fire a "click" event because you cannot actually
click on them.

If I manually add href="#" to the generated html, the links all work fine.

I opened another issue as requested.

On 12/31/11 1:49 PM, "Alex MacCaw"
<reply+i-2695287-c4e3af1c845cf05a375e5d0713d2e22cdff08d86-57294@reply.githu
b.com> wrote:
