### ISSUE TITLE
links generated by the scaffold generator are not clickable

### ISSUE THREAD

**Issue by goosetav** [spine/spine-rails#24]
FF/Mac - 8.0.1

Safari/Mac - 5.1.1

Chrome/Mac - 17.0.963.12 dev

(manually adding an href="#" makes them clickable)

**Comment by maccman** [comment]
Do you mean the mouse pointer isn't a hand? What do you mean by clickable?

**Comment by goosetav** [comment]
Yup, the pointer isn't a hand.

Generated code: http://cl.ly/150N09410T2T1N0V2E2W

Rendered result in chrome: http://cl.ly/0z0m0Y0Y0j433j2F360a

If I add in href attributes to the A tags, it works:
http://cl.ly/2v0l3l1G3d1B1i2p2d21

On 12/31/11 7:21 PM, "Alex MacCaw"
<reply+i-2696410-ec6e1cf9bae90a43d9c76c405a42633a5a62652f-57294@reply.githu
b.com> wrote:

**Comment by maccman** [comment]
Can I just confirm. When you click on the links, the page doesn't navigate correctly?

**Comment by goosetav** [comment]
Correct -- when I click the links, nothing happens at all.

On 12/31/11 7:27 PM, "Alex MacCaw"
<reply+i-2696410-ec6e1cf9bae90a43d9c76c405a42633a5a62652f-57294@reply.githu
b.com> wrote:

**Comment by maccman** [comment]
That's pretty odd - are there any error messages in the console?

**Comment by goosetav** [comment]
Nope, no errors in the console

On 12/31/11 7:54 PM, "Alex MacCaw"
<reply+i-2696410-ec6e1cf9bae90a43d9c76c405a42633a5a62652f-57294@reply.githu
b.com> wrote:

**Comment by goosetav** [comment]
OK. I must be going crazy. It is working, I must have been not quite
clicking the text or something.

The cursor still doesn't turn into a hand, just a text-selector, but it
does work.

On 12/31/11 7:54 PM, "Alex MacCaw"
<reply+i-2696410-ec6e1cf9bae90a43d9c76c405a42633a5a62652f-57294@reply.githu
b.com> wrote:
