### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by zohararad** [spine/spine-rails#43]
@maccman @benhainez How can we push a new build of the gem with latest version of Spine?

**Comment by shanear** [comment]
I'm interested in this too. I'm really in need of this fix: https://github.com/spine/spine/issues/460.

Is there an easy way to do this?

**Comment by zohararad** [comment]
I don't have ownership of the Gem itself, so its up to @maccman to either release or provide me and @benhainez with permission to release the Gem

**Comment by jackjennings** [comment]
+1

**Comment by hrigu** [comment]
+1
I ended up removing the gem and adding spine.js to vendor/assets/javascripts/spine manually

**Comment by maccman** [comment]
Done.
