### ISSUE TITLE
Vendored Spine version is inconsistent

### ISSUE THREAD

**Issue by jcarlson** [spine/spine-rails#47]
The latest version of this gem advertises to vendor Spine v1.1.0, however, there are some inconsistencies between the vendored version of Spine in this gem and the main Spine repository.

For example, in this gem:
https://github.com/spine/spine-rails/blob/v0.1.1/vendor/assets/javascripts/spine.coffee#L141

But in the main Spine repo:
https://github.com/spine/spine/blob/v1.1.0/src/spine.coffee#L141

Notably this means that https://github.com/spine/spine/issues/460 is fixed if I use the repository source code, but broken if I use the gem.

As a workaround, I can of course copy the Spine source files into my Rails app at `vendor/assets/javascripts`, but who wants to do that? :-)

Any chance you could cut a new gem to bring the vendored Spine source inline with the main Spine repo?

**Comment by zohararad** [comment]
@jcarlson alas, me and @benjaminhainez don't have permissions to publish the gem to Rubygems, so cutting a new gem that keeps up to date with Spine's repo is a bit of a pain. I ended up using code from the repo without the gem as well

**Comment by whatyoubendoing** [comment]
You do have the option off referencing github in your Gemfile eg.

``` ruby
gem 'spine-rails', github: 'spine/spine-rails', branch: 'master'
```
